sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '4'
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
script:
  - npm test
after_success:
  - npm run semantic-release
  - npm run coveralls
  - 'ls && ls dist'
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
